name: tremelique
channels:
  - conda-forge
dependencies:
  - python==3.13
  - pip
  # Build
  - twine
  - python-build
  # Run
  - numpy
  - numba
  - h5py
  - matplotlib
  - ipython
  - ipywidgets
  - rich
  - ffmpeg
  # Test
  - pytest
  - pytest-cov
  - pytest-mpl
  - coverage
  # Documentation
  - sphinx==7.2.*
  - numpydoc==1.7.*
  - sphinx-book-theme==1.1.*
  - sphinx-copybutton==0.5.*
  - sphinx-design==0.5.*
  - jupyter-sphinx==0.5.*
  # Style
  - ruff
  - zizmor
  - pip:
    - burocrata
